### ISSUE TITLE
Voicepack not working in Sepulcher Raid

### ISSUE THREAD

**Issue by gwenskey** [DeadlyBossMods/DBM-Voicepack-VEM#14]
Hello! I've had this voice pack since Castle Nathria, recently with the new raid it hasn't been working at all. I thought initially that DBM just wasn't updated enough, but today I tried a different voice pack and it works. I have this voicepack enabled in Addons, and selected properly in DBM, it's just not playing any of the warnings I've become reliant on. I found a similar post in the DBM Discord too.
Thank you for your help :)

**Comment by gwenskey** [comment]
![Screen Shot 2022-03-18 at 4 09 24 AM](https://user-images.githubusercontent.com/101865351/158974009-f0cdd6bf-ab35-4d55-896e-d3be8f7ba09c.png)

**Comment by MysticalOS** [comment]
VEM is probably disabled in addons list itself. VEM was especially coded so that user can also disable it by disabling the addon without it removed from the list. I'd be willing to bet yours is disabled (ie shows no checkbox, or a silver one which means disabled on current char but enabled on another one)

**Comment by gwenskey** [comment]
That's not the case. It is enabled for all characters and Load Out of Date Addons is checked too.

**Comment by QartemisT** [comment]
@gwenskey Is this still the case?

**Comment by gwenskey** [comment]
It was an issue on DBMs side where the raid IDs from Beta had changed since Release. It’s fixed. Thank you.

**Comment by QartemisT** [comment]
Wonderful to hear! Closing this issue as resolved.
